services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached

    command: sleep infinity

    network_mode: service:db

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    network_mode: host

  pgadmin:
    image: dpage/pgadmin4:latest
    configs:
      - source: pgadmin-pgpass
        target: /config/pgpass
        uid: "5050"
        gid: "5050"
        mode: "0400"
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: "0444"
    depends_on:
      db:
        condition: service_started
    environment:
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: student@cosc1301.local
      PGADMIN_DEFAULT_PASSWORD: password
      POSTGRES_DB: cosc1301
      POSTGTRES_HOST: db
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
    ports:
      - "8080:80"

configs:
  pgadmin-pgpass:
    content: |
      db:5432:*:postgres:password
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Class Database",
            "Group": "Servers",
            "Host": "db",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "PassFile": "/config/pgpass"
            }
          }
        }

volumes:
  postgres-data: